PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS desks;

CREATE TABLE desks (
    userid INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    macaddress TEXT NOT NULL,
    user TEXT NOT NULL,
    name TEXT NOT NULL,
    room TEXT NOT NULL
);

DROP TABLE IF EXISTS hights;

CREATE TABLE hights (
    hightid INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userid INTEGER NOT NULL,
    hight REAL NOT NULL
);