PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    userid INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username TEXT NOT NULL,
    passwd TEXT NOT NULL,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    room TEXT NOT NULL,
    status INTEGER NOT NULL,
    desksid INTEGER
);

DROP TABLE IF EXISTS desks;
CREATE TABLE desks (
    deskid INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    macaddress TEXT NOT NULL,
    userid INTEGER NOT NULL
);

DROP TABLE IF EXISTS hights;
CREATE TABLE hights (
    hightid INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userid INTEGER NOT NULL,
    hight REAL NOT NULL
);